CREATE TABLE dream_user
   (    
  ID int not null auto_increment, 
  GMT_CREATE datetime NOT NULL, 
  CREATOR VARCHAR(128) NOT NULL, 
  GMT_MODIFIED datetime NOT NULL, 
  MODIFIER VARCHAR(128) NOT NULL, 
  IS_DELETED CHAR(1) NOT NULL,  

  NAME VARCHAR(45) NOT NULL,
  NICK VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  SEX CHAR(1),
  PROVINCE_CODE VARCHAR(7) NOT NULL,
  CITY_CODE VARCHAR(7) NOT NULL,  
  EMAIL VARCHAR(45) NOT NULL,
  MOBILE_PHONE VARCHAR(11) NOT NULL,
  INTRODUCE VARCHAR(2000) NOT NULL, 
  TAG BIGINT NOT NULL,  
    
  primary key(id)
) ; 
 
CREATE TABLE dream_user_experience
   (    
       ID int not null auto_increment, 
  GMT_CREATE datetime NOT NULL, 
  CREATOR VARCHAR(128) NOT NULL, 
  GMT_MODIFIED datetime NOT NULL, 
  MODIFIER VARCHAR(128) NOT NULL, 
  IS_DELETED CHAR(1) NOT NULL,  
  USER_ID BIGINT NOT NULL,
  ORDER_INDEX INT NOT NULL,
  START_YEAR VARCHAR(5) NOT NULL,
  START_MONTH VARCHAR(3) NOT NULL, 
  END_YEAR VARCHAR(5),
  END_DATE VARCHAR(5),   
  EXPERIENCE VARCHAR(400) NOT NULL,   
  PROFESSION VARCHAR(100),
  primary key(id)
) ; 

CREATE TABLE dream_skill
   (    
   ID int not null auto_increment, 
  GMT_CREATE datetime NOT NULL, 
  CREATOR VARCHAR(128) NOT NULL, 
  GMT_MODIFIED datetime NOT NULL, 
  MODIFIER VARCHAR(128) NOT NULL, 
  IS_DELETED CHAR(1) NOT NULL,   
  TITLE VARCHAR(20) NOT NULL, 
  SUB_TITLE VARCHAR(200) NOT NULL,  
  SKILL_STATUS INT NOT NULL,
  DOWN_BOUND_PRICE BIGINT NOT NULL,
  UP_BOUND_PRICE BIGINT NOT NULL,
  NORMAL_PRICE BIGINT NOT NULL,
  PER VARCHAR(45) NOT NULL,
  CATEGORY VARCHAR(20) NOT NULL, 
  PROPERTIES VARCHAR(2000) NOT NULL,  
  OPTIONS BIGINT NOT NULL, 
  SELLER_ID BIGINT NOT NULL,
  INTRODUCE VARCHAR(1000) NOT NULL,
  SOLD_QUANTITY BIGINT NOT NULL,  
  PROVINCE_CODE VARCHAR(10) NOT NULL,
  CITY_CODE VARCHAR(10) NOT NULL,
  COME_FEE BIGINT NOT NULL,
  SCHEDULE BIGINT NOT NULL, 
  primary key(id)
) ;  

CREATE TABLE dream_ORDER
   (    
       ID int not null auto_increment, 
  GMT_CREATE datetime NOT NULL, 
  CREATOR VARCHAR(128) NOT NULL, 
  GMT_MODIFIED datetime NOT NULL, 
  MODIFIER VARCHAR(128) NOT NULL, 
  IS_DELETED CHAR(1) NOT NULL,  

  ORDER_ID BIGINT NOT NULL,
  SKILL_ID BIGINT NOT NULL,
  SKILL_NAME VARCHAR(20) NOT NULL,
  SELLER_ID BIGINT NOT NULL,
  SELLER_NICK varchar(20) NOT NULL,
  BUYER_ID BIGINT NOT NULL,
  BUYER_NICK varchar(20) NOT NULL,    
  MEETING_TYPE INT NOT NULL,
  AMOUNT INT NOT NULL, 
  VISIBLE_STATUS INT NOT NULL,
  PAY_STATUS INT NOT NULL,
  BIZ_TYPE VARCHAR(20) NOT NULL,
  PAY_TIME DATETIME NOT NULL,
  ATTRIBUTES VARCHAR(2000),  
  primary key(id)
) ; 

CREATE TABLE dream_RATE
   (    
       ID int not null auto_increment, 
  GMT_CREATE datetime NOT NULL, 
  CREATOR VARCHAR(128) NOT NULL, 
  GMT_MODIFIED datetime NOT NULL, 
  MODIFIER VARCHAR(128) NOT NULL, 
  IS_DELETED CHAR(1) NOT NULL,  

  SKILL_ID BIGINT NOT NULL,
  SKILL_SKU VARCHAR(200) NOT NULL,
  USER_ID BIGINT NOT NULL,
  DISPLAY_USER_NICK VARCHAR(200) NOT NULL,  
  RATE_TEXT VARCHAR(2000) NOT NULL, 
  RATE_TIME DATETIME NOT NULL,
  RATE_LEVEL INT NOT NULL,
  USEFUL_COUNT INT NOT NULL,
  UNUSEFUL_COUNT INT NOT NULL,
  primary key(id)
) ; 

CREATE TABLE UPLOAD_FILE
   (    
       ID int not null auto_increment, 
  GMT_CREATE datetime NOT NULL, 
  CREATOR VARCHAR(128) NOT NULL, 
  GMT_MODIFIED datetime NOT NULL, 
  MODIFIER VARCHAR(128) NOT NULL, 
  IS_DELETED CHAR(1) NOT NULL,  

  BUSINESS_ID BIGINT NOT NULL, 
  BUSINESS_TYPE VARCHAR(200) NOT NULL,
  FILE_NAME VARCHAR(200) NOT NULL,
  URL VARCHAR(200) NOT NULL,
  STATUS VARCHAR(20) NOT NULL,
  STORAGE_TYPE VARCHAR(6) NOT NULL,
  SIZE_TYPE VARCHAR(10) NOT NULL,
  primary key(id)
) ; 

CREATE TABLE DREAM_OPINION
   (    
       ID int not null auto_increment, 
  GMT_CREATE datetime NOT NULL, 
  CREATOR VARCHAR(128) NOT NULL, 
  GMT_MODIFIED datetime NOT NULL, 
  MODIFIER VARCHAR(128) NOT NULL, 
  IS_DELETED CHAR(1) NOT NULL,  

  NAME VARCHAR(200) NOT NULL, 
  EMAIL VARCHAR(200) NOT NULL,
  SUBJECT VARCHAR(200) NOT NULL,
  CONTENT VARCHAR(200) NOT NULL, 
  primary key(id)
) ; 


















