package com.sven.dream.dal.trade.mapper;

import com.sven.dream.dal.trade.DreamRateDo;

public interface DreamRateDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_RATE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_RATE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    int insert(DreamRateDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_RATE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    int insertSelective(DreamRateDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_RATE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    DreamRateDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_RATE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    int updateByPrimaryKeySelective(DreamRateDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_RATE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    int updateByPrimaryKey(DreamRateDo record);
}