package com.sven.dream.dal.trade.mapper;

import com.sven.dream.dal.trade.DreamSkillDo;

public interface DreamSkillDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_SKILL
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_SKILL
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    int insert(DreamSkillDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_SKILL
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    int insertSelective(DreamSkillDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_SKILL
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    DreamSkillDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_SKILL
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    int updateByPrimaryKeySelective(DreamSkillDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_SKILL
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    int updateByPrimaryKey(DreamSkillDo record);
}