package com.sven.dream.dal.trade.mapper;

import com.sven.dream.dal.trade.DreamOrderDo;

public interface DreamOrderDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_ORDER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_ORDER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    int insert(DreamOrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_ORDER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    int insertSelective(DreamOrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_ORDER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    DreamOrderDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_ORDER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    int updateByPrimaryKeySelective(DreamOrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_ORDER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    int updateByPrimaryKey(DreamOrderDo record);
}