package com.sven.dream.dal.user.mapper;

import com.sven.dream.dal.user.DreamOpinionDo;

public interface DreamOpinionDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DREAM_OPINION
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DREAM_OPINION
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    int insert(DreamOpinionDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DREAM_OPINION
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    int insertSelective(DreamOpinionDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DREAM_OPINION
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    DreamOpinionDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DREAM_OPINION
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    int updateByPrimaryKeySelective(DreamOpinionDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DREAM_OPINION
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    int updateByPrimaryKey(DreamOpinionDo record);
}