package com.sven.dream.dal.user.mapper;

import com.sven.dream.dal.user.DreamUserDo;

public interface DreamUserDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    int insert(DreamUserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    int insertSelective(DreamUserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    DreamUserDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    int updateByPrimaryKeySelective(DreamUserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dream_user
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    int updateByPrimaryKey(DreamUserDo record);
}