package com.sven.dream.dal.blog;

import java.util.Date;

import com.sven.dream.base.entity.DreamDo;

public class BlogDo extends DreamDo{
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_blog.TITLE
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_blog.CONTENT
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_blog.PUBLISH_TIME
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_blog.USER_ID
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_blog.CATEGORY_ID
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_blog.KEYWORD
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    private String keyword;
  
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_blog.TITLE
     *
     * @return the value of musik_blog.TITLE
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_blog.TITLE
     *
     * @param title the value for musik_blog.TITLE
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_blog.CONTENT
     *
     * @return the value of musik_blog.CONTENT
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_blog.CONTENT
     *
     * @param content the value for musik_blog.CONTENT
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_blog.PUBLISH_TIME
     *
     * @return the value of musik_blog.PUBLISH_TIME
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_blog.PUBLISH_TIME
     *
     * @param publishTime the value for musik_blog.PUBLISH_TIME
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_blog.USER_ID
     *
     * @return the value of musik_blog.USER_ID
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_blog.USER_ID
     *
     * @param userId the value for musik_blog.USER_ID
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_blog.CATEGORY_ID
     *
     * @return the value of musik_blog.CATEGORY_ID
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_blog.CATEGORY_ID
     *
     * @param categoryId the value for musik_blog.CATEGORY_ID
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_blog.KEYWORD
     *
     * @return the value of musik_blog.KEYWORD
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_blog.KEYWORD
     *
     * @param keyword the value for musik_blog.KEYWORD
     *
     * @mbggenerated Thu Sep 10 23:32:18 CST 2015
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }
}