package com.sven.dream.dal.music;

import java.util.Date;

import com.sven.dream.base.entity.DreamDo;

public class AlbumDo extends DreamDo{
     
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_album.ALBUM_NAME
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    private String albumName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_album.PUBLISH_DATE
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    private Date publishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_album.SINGER_ID
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    private Long singerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_album.TRY_LISTEN
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    private Long tryListen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_album.LANGUAGE
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    private Integer language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_album.INTRODUCE
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_album.ALBUM_STYLE
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    private String albumStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_album.ALBUM_TYPE
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    private String albumType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_album.category
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    private String category;
 
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_album.ALBUM_NAME
     *
     * @return the value of musik_album.ALBUM_NAME
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public String getAlbumName() {
        return albumName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_album.ALBUM_NAME
     *
     * @param albumName the value for musik_album.ALBUM_NAME
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public void setAlbumName(String albumName) {
        this.albumName = albumName == null ? null : albumName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_album.PUBLISH_DATE
     *
     * @return the value of musik_album.PUBLISH_DATE
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public Date getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_album.PUBLISH_DATE
     *
     * @param publishDate the value for musik_album.PUBLISH_DATE
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_album.SINGER_ID
     *
     * @return the value of musik_album.SINGER_ID
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public Long getSingerId() {
        return singerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_album.SINGER_ID
     *
     * @param singerId the value for musik_album.SINGER_ID
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public void setSingerId(Long singerId) {
        this.singerId = singerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_album.TRY_LISTEN
     *
     * @return the value of musik_album.TRY_LISTEN
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public Long getTryListen() {
        return tryListen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_album.TRY_LISTEN
     *
     * @param tryListen the value for musik_album.TRY_LISTEN
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public void setTryListen(Long tryListen) {
        this.tryListen = tryListen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_album.LANGUAGE
     *
     * @return the value of musik_album.LANGUAGE
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public Integer getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_album.LANGUAGE
     *
     * @param language the value for musik_album.LANGUAGE
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public void setLanguage(Integer language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_album.INTRODUCE
     *
     * @return the value of musik_album.INTRODUCE
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_album.INTRODUCE
     *
     * @param introduce the value for musik_album.INTRODUCE
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_album.ALBUM_STYLE
     *
     * @return the value of musik_album.ALBUM_STYLE
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public String getAlbumStyle() {
        return albumStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_album.ALBUM_STYLE
     *
     * @param albumStyle the value for musik_album.ALBUM_STYLE
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public void setAlbumStyle(String albumStyle) {
        this.albumStyle = albumStyle == null ? null : albumStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_album.ALBUM_TYPE
     *
     * @return the value of musik_album.ALBUM_TYPE
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public String getAlbumType() {
        return albumType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_album.ALBUM_TYPE
     *
     * @param albumType the value for musik_album.ALBUM_TYPE
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public void setAlbumType(String albumType) {
        this.albumType = albumType == null ? null : albumType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_album.category
     *
     * @return the value of musik_album.category
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_album.category
     *
     * @param category the value for musik_album.category
     *
     * @mbggenerated Wed Sep 23 23:30:36 CST 2015
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }
}