package com.sven.dream.dal.music;
 
import com.sven.dream.base.entity.DreamDo;

public class MusicMtvDo extends DreamDo{
  
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_mtv.SINGER_ID
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private Long singerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_mtv.SONG_NAME
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private String songName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_mtv.SONG_LYRIC
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private String songLyric;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_mtv.MUSIC_TIME
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private Integer musicTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_mtv.CLICK_GOOD
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private Integer clickGood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_mtv.INTRODUCE
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_mtv.AUTHORS
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private String authors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_mtv.COMPOSE
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private String compose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_mtv.ARRANGER
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private String arranger;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_mtv.VIDEO_LINK
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private String videoLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_mtv.RELATION_MUSIC
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private Long relationMusic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_mtv.ALBUM_ID
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private Long albumId;
 
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_mtv.SINGER_ID
     *
     * @return the value of musik_mtv.SINGER_ID
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public Long getSingerId() {
        return singerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_mtv.SINGER_ID
     *
     * @param singerId the value for musik_mtv.SINGER_ID
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setSingerId(Long singerId) {
        this.singerId = singerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_mtv.SONG_NAME
     *
     * @return the value of musik_mtv.SONG_NAME
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public String getSongName() {
        return songName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_mtv.SONG_NAME
     *
     * @param songName the value for musik_mtv.SONG_NAME
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setSongName(String songName) {
        this.songName = songName == null ? null : songName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_mtv.SONG_LYRIC
     *
     * @return the value of musik_mtv.SONG_LYRIC
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public String getSongLyric() {
        return songLyric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_mtv.SONG_LYRIC
     *
     * @param songLyric the value for musik_mtv.SONG_LYRIC
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setSongLyric(String songLyric) {
        this.songLyric = songLyric == null ? null : songLyric.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_mtv.MUSIC_TIME
     *
     * @return the value of musik_mtv.MUSIC_TIME
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public Integer getMusicTime() {
        return musicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_mtv.MUSIC_TIME
     *
     * @param musicTime the value for musik_mtv.MUSIC_TIME
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setMusicTime(Integer musicTime) {
        this.musicTime = musicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_mtv.CLICK_GOOD
     *
     * @return the value of musik_mtv.CLICK_GOOD
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public Integer getClickGood() {
        return clickGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_mtv.CLICK_GOOD
     *
     * @param clickGood the value for musik_mtv.CLICK_GOOD
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setClickGood(Integer clickGood) {
        this.clickGood = clickGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_mtv.INTRODUCE
     *
     * @return the value of musik_mtv.INTRODUCE
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_mtv.INTRODUCE
     *
     * @param introduce the value for musik_mtv.INTRODUCE
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_mtv.AUTHORS
     *
     * @return the value of musik_mtv.AUTHORS
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public String getAuthors() {
        return authors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_mtv.AUTHORS
     *
     * @param authors the value for musik_mtv.AUTHORS
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setAuthors(String authors) {
        this.authors = authors == null ? null : authors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_mtv.COMPOSE
     *
     * @return the value of musik_mtv.COMPOSE
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public String getCompose() {
        return compose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_mtv.COMPOSE
     *
     * @param compose the value for musik_mtv.COMPOSE
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setCompose(String compose) {
        this.compose = compose == null ? null : compose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_mtv.ARRANGER
     *
     * @return the value of musik_mtv.ARRANGER
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public String getArranger() {
        return arranger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_mtv.ARRANGER
     *
     * @param arranger the value for musik_mtv.ARRANGER
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setArranger(String arranger) {
        this.arranger = arranger == null ? null : arranger.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_mtv.VIDEO_LINK
     *
     * @return the value of musik_mtv.VIDEO_LINK
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public String getVideoLink() {
        return videoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_mtv.VIDEO_LINK
     *
     * @param videoLink the value for musik_mtv.VIDEO_LINK
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setVideoLink(String videoLink) {
        this.videoLink = videoLink == null ? null : videoLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_mtv.RELATION_MUSIC
     *
     * @return the value of musik_mtv.RELATION_MUSIC
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public Long getRelationMusic() {
        return relationMusic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_mtv.RELATION_MUSIC
     *
     * @param relationMusic the value for musik_mtv.RELATION_MUSIC
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setRelationMusic(Long relationMusic) {
        this.relationMusic = relationMusic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_mtv.ALBUM_ID
     *
     * @return the value of musik_mtv.ALBUM_ID
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public Long getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_mtv.ALBUM_ID
     *
     * @param albumId the value for musik_mtv.ALBUM_ID
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setAlbumId(Long albumId) {
        this.albumId = albumId;
    }
}