package com.sven.dream.dal.music;
 
import com.sven.dream.base.entity.DreamDo;

public class MusicDo extends DreamDo{
     
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_music.SINGER_ID
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private Long singerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_music.SONG_NAME
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private String songName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_music.SONG_LYRIC
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private String songLyric;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_music.MUSIC_TIME
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private Integer musicTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_music.CLICK_GOOD
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private Integer clickGood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_music.INTRODUCE
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_music.AUTHORS
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private String authors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_music.COMPOSE
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private String compose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_music.ARRANGER
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private String arranger;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_music.ALBUM_ID
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    private Long albumId;
 
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_music.SINGER_ID
     *
     * @return the value of musik_music.SINGER_ID
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public Long getSingerId() {
        return singerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_music.SINGER_ID
     *
     * @param singerId the value for musik_music.SINGER_ID
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setSingerId(Long singerId) {
        this.singerId = singerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_music.SONG_NAME
     *
     * @return the value of musik_music.SONG_NAME
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public String getSongName() {
        return songName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_music.SONG_NAME
     *
     * @param songName the value for musik_music.SONG_NAME
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setSongName(String songName) {
        this.songName = songName == null ? null : songName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_music.SONG_LYRIC
     *
     * @return the value of musik_music.SONG_LYRIC
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public String getSongLyric() {
        return songLyric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_music.SONG_LYRIC
     *
     * @param songLyric the value for musik_music.SONG_LYRIC
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setSongLyric(String songLyric) {
        this.songLyric = songLyric == null ? null : songLyric.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_music.MUSIC_TIME
     *
     * @return the value of musik_music.MUSIC_TIME
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public Integer getMusicTime() {
        return musicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_music.MUSIC_TIME
     *
     * @param musicTime the value for musik_music.MUSIC_TIME
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setMusicTime(Integer musicTime) {
        this.musicTime = musicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_music.CLICK_GOOD
     *
     * @return the value of musik_music.CLICK_GOOD
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public Integer getClickGood() {
        return clickGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_music.CLICK_GOOD
     *
     * @param clickGood the value for musik_music.CLICK_GOOD
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setClickGood(Integer clickGood) {
        this.clickGood = clickGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_music.INTRODUCE
     *
     * @return the value of musik_music.INTRODUCE
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_music.INTRODUCE
     *
     * @param introduce the value for musik_music.INTRODUCE
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_music.AUTHORS
     *
     * @return the value of musik_music.AUTHORS
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public String getAuthors() {
        return authors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_music.AUTHORS
     *
     * @param authors the value for musik_music.AUTHORS
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setAuthors(String authors) {
        this.authors = authors == null ? null : authors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_music.COMPOSE
     *
     * @return the value of musik_music.COMPOSE
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public String getCompose() {
        return compose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_music.COMPOSE
     *
     * @param compose the value for musik_music.COMPOSE
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setCompose(String compose) {
        this.compose = compose == null ? null : compose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_music.ARRANGER
     *
     * @return the value of musik_music.ARRANGER
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public String getArranger() {
        return arranger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_music.ARRANGER
     *
     * @param arranger the value for musik_music.ARRANGER
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setArranger(String arranger) {
        this.arranger = arranger == null ? null : arranger.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_music.ALBUM_ID
     *
     * @return the value of musik_music.ALBUM_ID
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public Long getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_music.ALBUM_ID
     *
     * @param albumId the value for musik_music.ALBUM_ID
     *
     * @mbggenerated Thu Sep 10 22:02:36 CST 2015
     */
    public void setAlbumId(Long albumId) {
        this.albumId = albumId;
    }
}