package com.sven.dream.dal.common;

import java.util.Date;

import com.sven.dream.base.entity.DreamDo;

public class DiscussDo extends DreamDo{
     
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_discuss.BUSINESS_ID
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    private Long businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_discuss.BUSINESS_TYPE
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    private String businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_discuss.USER_ID
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_discuss.RESPONSE
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    private String response;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_discuss.RESPONSE_TIME
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    private Date responseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_discuss.FOR_WHICH
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    private Long forWhich; 
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_discuss.BUSINESS_ID
     *
     * @return the value of musik_discuss.BUSINESS_ID
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_discuss.BUSINESS_ID
     *
     * @param businessId the value for musik_discuss.BUSINESS_ID
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_discuss.BUSINESS_TYPE
     *
     * @return the value of musik_discuss.BUSINESS_TYPE
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_discuss.BUSINESS_TYPE
     *
     * @param businessType the value for musik_discuss.BUSINESS_TYPE
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_discuss.USER_ID
     *
     * @return the value of musik_discuss.USER_ID
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_discuss.USER_ID
     *
     * @param userId the value for musik_discuss.USER_ID
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_discuss.RESPONSE
     *
     * @return the value of musik_discuss.RESPONSE
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public String getResponse() {
        return response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_discuss.RESPONSE
     *
     * @param response the value for musik_discuss.RESPONSE
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public void setResponse(String response) {
        this.response = response == null ? null : response.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_discuss.RESPONSE_TIME
     *
     * @return the value of musik_discuss.RESPONSE_TIME
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public Date getResponseTime() {
        return responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_discuss.RESPONSE_TIME
     *
     * @param responseTime the value for musik_discuss.RESPONSE_TIME
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public void setResponseTime(Date responseTime) {
        this.responseTime = responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_discuss.FOR_WHICH
     *
     * @return the value of musik_discuss.FOR_WHICH
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public Long getForWhich() {
        return forWhich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_discuss.FOR_WHICH
     *
     * @param forWhich the value for musik_discuss.FOR_WHICH
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public void setForWhich(Long forWhich) {
        this.forWhich = forWhich;
    }
}