package com.sven.dream.dal.common;
 
import com.sven.dream.base.entity.DreamDo;

public class MessageDo extends DreamDo{
    
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_message.RECEIVER
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    private Long receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_message.BUSINESS_ID
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    private Long businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_message.BUSINESS_TYPE
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    private String businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_message.MESSAGE_TYPE
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    private Integer messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_message.TITLE
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_message.CONTENT
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_message.STATUS
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_message.PROPERTIES
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    private String properties;
 
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_message.RECEIVER
     *
     * @return the value of musik_message.RECEIVER
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_message.RECEIVER
     *
     * @param receiver the value for musik_message.RECEIVER
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_message.BUSINESS_ID
     *
     * @return the value of musik_message.BUSINESS_ID
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_message.BUSINESS_ID
     *
     * @param businessId the value for musik_message.BUSINESS_ID
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_message.BUSINESS_TYPE
     *
     * @return the value of musik_message.BUSINESS_TYPE
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_message.BUSINESS_TYPE
     *
     * @param businessType the value for musik_message.BUSINESS_TYPE
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_message.MESSAGE_TYPE
     *
     * @return the value of musik_message.MESSAGE_TYPE
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public Integer getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_message.MESSAGE_TYPE
     *
     * @param messageType the value for musik_message.MESSAGE_TYPE
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_message.TITLE
     *
     * @return the value of musik_message.TITLE
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_message.TITLE
     *
     * @param title the value for musik_message.TITLE
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_message.CONTENT
     *
     * @return the value of musik_message.CONTENT
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_message.CONTENT
     *
     * @param content the value for musik_message.CONTENT
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_message.STATUS
     *
     * @return the value of musik_message.STATUS
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_message.STATUS
     *
     * @param status the value for musik_message.STATUS
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_message.PROPERTIES
     *
     * @return the value of musik_message.PROPERTIES
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public String getProperties() {
        return properties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_message.PROPERTIES
     *
     * @param properties the value for musik_message.PROPERTIES
     *
     * @mbggenerated Thu Sep 10 21:33:08 CST 2015
     */
    public void setProperties(String properties) {
        this.properties = properties == null ? null : properties.trim();
    }
}