package com.sven.dream.dal.common.mapper;

import com.sven.dream.dal.common.UploadFileDo;

public interface UploadFileDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UPLOAD_FILE
     *
     * @mbggenerated Tue Aug 04 17:11:32 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UPLOAD_FILE
     *
     * @mbggenerated Tue Aug 04 17:11:32 CST 2015
     */
    int insert(UploadFileDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UPLOAD_FILE
     *
     * @mbggenerated Tue Aug 04 17:11:32 CST 2015
     */
    int insertSelective(UploadFileDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UPLOAD_FILE
     *
     * @mbggenerated Tue Aug 04 17:11:32 CST 2015
     */
    UploadFileDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UPLOAD_FILE
     *
     * @mbggenerated Tue Aug 04 17:11:32 CST 2015
     */
    int updateByPrimaryKeySelective(UploadFileDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UPLOAD_FILE
     *
     * @mbggenerated Tue Aug 04 17:11:32 CST 2015
     */
    int updateByPrimaryKey(UploadFileDo record);
}