package com.sven.dream.dal.user;
 
import com.sven.dream.base.entity.DreamDo;

public class DreamOpinionDo extends DreamDo{
     
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DREAM_OPINION.NAME
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DREAM_OPINION.EMAIL
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DREAM_OPINION.SUBJECT
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DREAM_OPINION.CONTENT
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String content;
  
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DREAM_OPINION.NAME
     *
     * @return the value of DREAM_OPINION.NAME
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DREAM_OPINION.NAME
     *
     * @param name the value for DREAM_OPINION.NAME
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DREAM_OPINION.EMAIL
     *
     * @return the value of DREAM_OPINION.EMAIL
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DREAM_OPINION.EMAIL
     *
     * @param email the value for DREAM_OPINION.EMAIL
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DREAM_OPINION.SUBJECT
     *
     * @return the value of DREAM_OPINION.SUBJECT
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DREAM_OPINION.SUBJECT
     *
     * @param subject the value for DREAM_OPINION.SUBJECT
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DREAM_OPINION.CONTENT
     *
     * @return the value of DREAM_OPINION.CONTENT
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DREAM_OPINION.CONTENT
     *
     * @param content the value for DREAM_OPINION.CONTENT
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}