package com.sven.dream.dal.user;

import java.util.Date;

public class DreamUserDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.ID
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.GMT_CREATE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.CREATOR
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.GMT_MODIFIED
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.MODIFIER
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.IS_DELETED
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.TAG
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private Long tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.FIRST_NAME
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.LAST_NAME
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.SEX
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.IS_NAME_SECRET
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String isNameSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.PROVINCE_CODE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.CITY_CODE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.DISTRICT_CODE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String districtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.CAREER_ADDRESS
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String careerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.HOME_ADDRESS
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String homeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.EMAIL
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.MOBILE_PHONE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.INTRODUCE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String introduce;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.ID
     *
     * @return the value of dream_user.ID
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.ID
     *
     * @param id the value for dream_user.ID
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.GMT_CREATE
     *
     * @return the value of dream_user.GMT_CREATE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.GMT_CREATE
     *
     * @param gmtCreate the value for dream_user.GMT_CREATE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.CREATOR
     *
     * @return the value of dream_user.CREATOR
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.CREATOR
     *
     * @param creator the value for dream_user.CREATOR
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.GMT_MODIFIED
     *
     * @return the value of dream_user.GMT_MODIFIED
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.GMT_MODIFIED
     *
     * @param gmtModified the value for dream_user.GMT_MODIFIED
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.MODIFIER
     *
     * @return the value of dream_user.MODIFIER
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.MODIFIER
     *
     * @param modifier the value for dream_user.MODIFIER
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.IS_DELETED
     *
     * @return the value of dream_user.IS_DELETED
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.IS_DELETED
     *
     * @param isDeleted the value for dream_user.IS_DELETED
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.TAG
     *
     * @return the value of dream_user.TAG
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public Long getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.TAG
     *
     * @param tag the value for dream_user.TAG
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setTag(Long tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.FIRST_NAME
     *
     * @return the value of dream_user.FIRST_NAME
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.FIRST_NAME
     *
     * @param firstName the value for dream_user.FIRST_NAME
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.LAST_NAME
     *
     * @return the value of dream_user.LAST_NAME
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.LAST_NAME
     *
     * @param lastName the value for dream_user.LAST_NAME
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.SEX
     *
     * @return the value of dream_user.SEX
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.SEX
     *
     * @param sex the value for dream_user.SEX
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.IS_NAME_SECRET
     *
     * @return the value of dream_user.IS_NAME_SECRET
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getIsNameSecret() {
        return isNameSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.IS_NAME_SECRET
     *
     * @param isNameSecret the value for dream_user.IS_NAME_SECRET
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setIsNameSecret(String isNameSecret) {
        this.isNameSecret = isNameSecret == null ? null : isNameSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.PROVINCE_CODE
     *
     * @return the value of dream_user.PROVINCE_CODE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.PROVINCE_CODE
     *
     * @param provinceCode the value for dream_user.PROVINCE_CODE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.CITY_CODE
     *
     * @return the value of dream_user.CITY_CODE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.CITY_CODE
     *
     * @param cityCode the value for dream_user.CITY_CODE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.DISTRICT_CODE
     *
     * @return the value of dream_user.DISTRICT_CODE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.DISTRICT_CODE
     *
     * @param districtCode the value for dream_user.DISTRICT_CODE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode == null ? null : districtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.CAREER_ADDRESS
     *
     * @return the value of dream_user.CAREER_ADDRESS
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getCareerAddress() {
        return careerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.CAREER_ADDRESS
     *
     * @param careerAddress the value for dream_user.CAREER_ADDRESS
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setCareerAddress(String careerAddress) {
        this.careerAddress = careerAddress == null ? null : careerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.HOME_ADDRESS
     *
     * @return the value of dream_user.HOME_ADDRESS
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.HOME_ADDRESS
     *
     * @param homeAddress the value for dream_user.HOME_ADDRESS
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress == null ? null : homeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.EMAIL
     *
     * @return the value of dream_user.EMAIL
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.EMAIL
     *
     * @param email the value for dream_user.EMAIL
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.MOBILE_PHONE
     *
     * @return the value of dream_user.MOBILE_PHONE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.MOBILE_PHONE
     *
     * @param mobilePhone the value for dream_user.MOBILE_PHONE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.INTRODUCE
     *
     * @return the value of dream_user.INTRODUCE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.INTRODUCE
     *
     * @param introduce the value for dream_user.INTRODUCE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }
}