package com.sven.dream.dal.user;

import java.util.Date;

public class DreamOpinionDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DREAM_OPINION.ID
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DREAM_OPINION.GMT_CREATE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DREAM_OPINION.CREATOR
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DREAM_OPINION.GMT_MODIFIED
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DREAM_OPINION.MODIFIER
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DREAM_OPINION.IS_DELETED
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DREAM_OPINION.NAME
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DREAM_OPINION.EMAIL
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DREAM_OPINION.SUBJECT
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DREAM_OPINION.CONTENT
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DREAM_OPINION.ID
     *
     * @return the value of DREAM_OPINION.ID
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DREAM_OPINION.ID
     *
     * @param id the value for DREAM_OPINION.ID
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DREAM_OPINION.GMT_CREATE
     *
     * @return the value of DREAM_OPINION.GMT_CREATE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DREAM_OPINION.GMT_CREATE
     *
     * @param gmtCreate the value for DREAM_OPINION.GMT_CREATE
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DREAM_OPINION.CREATOR
     *
     * @return the value of DREAM_OPINION.CREATOR
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DREAM_OPINION.CREATOR
     *
     * @param creator the value for DREAM_OPINION.CREATOR
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DREAM_OPINION.GMT_MODIFIED
     *
     * @return the value of DREAM_OPINION.GMT_MODIFIED
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DREAM_OPINION.GMT_MODIFIED
     *
     * @param gmtModified the value for DREAM_OPINION.GMT_MODIFIED
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DREAM_OPINION.MODIFIER
     *
     * @return the value of DREAM_OPINION.MODIFIER
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DREAM_OPINION.MODIFIER
     *
     * @param modifier the value for DREAM_OPINION.MODIFIER
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DREAM_OPINION.IS_DELETED
     *
     * @return the value of DREAM_OPINION.IS_DELETED
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DREAM_OPINION.IS_DELETED
     *
     * @param isDeleted the value for DREAM_OPINION.IS_DELETED
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DREAM_OPINION.NAME
     *
     * @return the value of DREAM_OPINION.NAME
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DREAM_OPINION.NAME
     *
     * @param name the value for DREAM_OPINION.NAME
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DREAM_OPINION.EMAIL
     *
     * @return the value of DREAM_OPINION.EMAIL
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DREAM_OPINION.EMAIL
     *
     * @param email the value for DREAM_OPINION.EMAIL
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DREAM_OPINION.SUBJECT
     *
     * @return the value of DREAM_OPINION.SUBJECT
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DREAM_OPINION.SUBJECT
     *
     * @param subject the value for DREAM_OPINION.SUBJECT
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DREAM_OPINION.CONTENT
     *
     * @return the value of DREAM_OPINION.CONTENT
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DREAM_OPINION.CONTENT
     *
     * @param content the value for DREAM_OPINION.CONTENT
     *
     * @mbggenerated Tue Aug 04 17:01:23 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}