package com.sven.dream.dal.user;

import com.sven.dream.base.entity.DreamDo;

public class DreamUserExperienceDo extends DreamDo{
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user_experience.USER_ID
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user_experience.ORDER_INDEX
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    private Integer orderIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user_experience.START_YEAR
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    private String startYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user_experience.START_MONTH
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    private String startMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user_experience.END_YEAR
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    private String endYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user_experience.END_DATE
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user_experience.EXPERIENCE
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    private String experience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user_experience.PROFESSION
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    private String profession;
 
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user_experience.USER_ID
     *
     * @return the value of dream_user_experience.USER_ID
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user_experience.USER_ID
     *
     * @param userId the value for dream_user_experience.USER_ID
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user_experience.ORDER_INDEX
     *
     * @return the value of dream_user_experience.ORDER_INDEX
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    public Integer getOrderIndex() {
        return orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user_experience.ORDER_INDEX
     *
     * @param orderIndex the value for dream_user_experience.ORDER_INDEX
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    public void setOrderIndex(Integer orderIndex) {
        this.orderIndex = orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user_experience.START_YEAR
     *
     * @return the value of dream_user_experience.START_YEAR
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    public String getStartYear() {
        return startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user_experience.START_YEAR
     *
     * @param startYear the value for dream_user_experience.START_YEAR
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    public void setStartYear(String startYear) {
        this.startYear = startYear == null ? null : startYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user_experience.START_MONTH
     *
     * @return the value of dream_user_experience.START_MONTH
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    public String getStartMonth() {
        return startMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user_experience.START_MONTH
     *
     * @param startMonth the value for dream_user_experience.START_MONTH
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    public void setStartMonth(String startMonth) {
        this.startMonth = startMonth == null ? null : startMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user_experience.END_YEAR
     *
     * @return the value of dream_user_experience.END_YEAR
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    public String getEndYear() {
        return endYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user_experience.END_YEAR
     *
     * @param endYear the value for dream_user_experience.END_YEAR
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    public void setEndYear(String endYear) {
        this.endYear = endYear == null ? null : endYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user_experience.END_DATE
     *
     * @return the value of dream_user_experience.END_DATE
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user_experience.END_DATE
     *
     * @param endDate the value for dream_user_experience.END_DATE
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user_experience.EXPERIENCE
     *
     * @return the value of dream_user_experience.EXPERIENCE
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    public String getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user_experience.EXPERIENCE
     *
     * @param experience the value for dream_user_experience.EXPERIENCE
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    public void setExperience(String experience) {
        this.experience = experience == null ? null : experience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user_experience.PROFESSION
     *
     * @return the value of dream_user_experience.PROFESSION
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user_experience.PROFESSION
     *
     * @param profession the value for dream_user_experience.PROFESSION
     *
     * @mbggenerated Mon Aug 17 13:16:26 CST 2015
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }
}