package com.sven.dream.dal.user;
 
import com.sven.dream.base.entity.DreamDo;

public class DreamUserDo extends DreamDo{
     
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.NAME
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.NICK
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.PASSWORD
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.SEX
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.PROVINCE_CODE
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.CITY_CODE
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.EMAIL
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.MOBILE_PHONE
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.INTRODUCE
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_user.TAG
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    private Long tag;
  
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.NAME
     *
     * @return the value of dream_user.NAME
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.NAME
     *
     * @param name the value for dream_user.NAME
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.NICK
     *
     * @return the value of dream_user.NICK
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.NICK
     *
     * @param nick the value for dream_user.NICK
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.PASSWORD
     *
     * @return the value of dream_user.PASSWORD
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.PASSWORD
     *
     * @param password the value for dream_user.PASSWORD
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.SEX
     *
     * @return the value of dream_user.SEX
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.SEX
     *
     * @param sex the value for dream_user.SEX
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.PROVINCE_CODE
     *
     * @return the value of dream_user.PROVINCE_CODE
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.PROVINCE_CODE
     *
     * @param provinceCode the value for dream_user.PROVINCE_CODE
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.CITY_CODE
     *
     * @return the value of dream_user.CITY_CODE
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.CITY_CODE
     *
     * @param cityCode the value for dream_user.CITY_CODE
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.EMAIL
     *
     * @return the value of dream_user.EMAIL
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.EMAIL
     *
     * @param email the value for dream_user.EMAIL
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.MOBILE_PHONE
     *
     * @return the value of dream_user.MOBILE_PHONE
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.MOBILE_PHONE
     *
     * @param mobilePhone the value for dream_user.MOBILE_PHONE
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.INTRODUCE
     *
     * @return the value of dream_user.INTRODUCE
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.INTRODUCE
     *
     * @param introduce the value for dream_user.INTRODUCE
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_user.TAG
     *
     * @return the value of dream_user.TAG
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public Long getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_user.TAG
     *
     * @param tag the value for dream_user.TAG
     *
     * @mbggenerated Thu Aug 13 11:40:01 CST 2015
     */
    public void setTag(Long tag) {
        this.tag = tag;
    }
}