package com.sven.dream.dal.user;
 
import com.sven.dream.base.entity.DreamDo;

public class UserDo extends DreamDo{
     
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_user.LOGIN_NAME
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_user.PASSWORD
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_user.NICK
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_user.SEX
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_user.ONLINE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    private String online;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_user.ROLE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_user.PROVINCE_CODE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_user.CITY_CODE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_user.EMAIL
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_user.MOBILE_PHONE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_user.INTRODUCE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_user.JOB
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_user.WEIBO_ACCOUNT
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    private String weiboAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musik_user.WEBSITE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    private String website;
  
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_user.LOGIN_NAME
     *
     * @return the value of musik_user.LOGIN_NAME
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_user.LOGIN_NAME
     *
     * @param loginName the value for musik_user.LOGIN_NAME
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_user.PASSWORD
     *
     * @return the value of musik_user.PASSWORD
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_user.PASSWORD
     *
     * @param password the value for musik_user.PASSWORD
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_user.NICK
     *
     * @return the value of musik_user.NICK
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_user.NICK
     *
     * @param nick the value for musik_user.NICK
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_user.SEX
     *
     * @return the value of musik_user.SEX
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_user.SEX
     *
     * @param sex the value for musik_user.SEX
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_user.ONLINE
     *
     * @return the value of musik_user.ONLINE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public String getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_user.ONLINE
     *
     * @param online the value for musik_user.ONLINE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public void setOnline(String online) {
        this.online = online == null ? null : online.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_user.ROLE
     *
     * @return the value of musik_user.ROLE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_user.ROLE
     *
     * @param role the value for musik_user.ROLE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_user.PROVINCE_CODE
     *
     * @return the value of musik_user.PROVINCE_CODE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_user.PROVINCE_CODE
     *
     * @param provinceCode the value for musik_user.PROVINCE_CODE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_user.CITY_CODE
     *
     * @return the value of musik_user.CITY_CODE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_user.CITY_CODE
     *
     * @param cityCode the value for musik_user.CITY_CODE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_user.EMAIL
     *
     * @return the value of musik_user.EMAIL
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_user.EMAIL
     *
     * @param email the value for musik_user.EMAIL
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_user.MOBILE_PHONE
     *
     * @return the value of musik_user.MOBILE_PHONE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_user.MOBILE_PHONE
     *
     * @param mobilePhone the value for musik_user.MOBILE_PHONE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_user.INTRODUCE
     *
     * @return the value of musik_user.INTRODUCE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_user.INTRODUCE
     *
     * @param introduce the value for musik_user.INTRODUCE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_user.JOB
     *
     * @return the value of musik_user.JOB
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_user.JOB
     *
     * @param job the value for musik_user.JOB
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_user.WEIBO_ACCOUNT
     *
     * @return the value of musik_user.WEIBO_ACCOUNT
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public String getWeiboAccount() {
        return weiboAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_user.WEIBO_ACCOUNT
     *
     * @param weiboAccount the value for musik_user.WEIBO_ACCOUNT
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public void setWeiboAccount(String weiboAccount) {
        this.weiboAccount = weiboAccount == null ? null : weiboAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musik_user.WEBSITE
     *
     * @return the value of musik_user.WEBSITE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musik_user.WEBSITE
     *
     * @param website the value for musik_user.WEBSITE
     *
     * @mbggenerated Thu Sep 10 21:53:07 CST 2015
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }
}