package com.sven.dream.dal.trade;

import java.util.Date;

public class DreamOrderDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.GMT_CREATE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.CREATOR
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.GMT_MODIFIED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.MODIFIER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.IS_DELETED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.ORDER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.SKILL_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Long skillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.SKILL_NAME
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String skillName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.SELLER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.SELLER_NICK
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String sellerNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.BUYER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Long buyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.BUYER_NICK
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String buyerNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.RATE_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Long rateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.MEETING_TYPE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Integer meetingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.AMOUNT
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.ORDER_STATUS
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.VISIBLE_STATUS
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Integer visibleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.PAY_STATUS
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.BIZ_TYPE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.PAY_TIME
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_ORDER.ATTRIBUTES
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String attributes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.ID
     *
     * @return the value of dream_ORDER.ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.ID
     *
     * @param id the value for dream_ORDER.ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.GMT_CREATE
     *
     * @return the value of dream_ORDER.GMT_CREATE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.GMT_CREATE
     *
     * @param gmtCreate the value for dream_ORDER.GMT_CREATE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.CREATOR
     *
     * @return the value of dream_ORDER.CREATOR
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.CREATOR
     *
     * @param creator the value for dream_ORDER.CREATOR
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.GMT_MODIFIED
     *
     * @return the value of dream_ORDER.GMT_MODIFIED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.GMT_MODIFIED
     *
     * @param gmtModified the value for dream_ORDER.GMT_MODIFIED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.MODIFIER
     *
     * @return the value of dream_ORDER.MODIFIER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.MODIFIER
     *
     * @param modifier the value for dream_ORDER.MODIFIER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.IS_DELETED
     *
     * @return the value of dream_ORDER.IS_DELETED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.IS_DELETED
     *
     * @param isDeleted the value for dream_ORDER.IS_DELETED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.ORDER_ID
     *
     * @return the value of dream_ORDER.ORDER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.ORDER_ID
     *
     * @param orderId the value for dream_ORDER.ORDER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.SKILL_ID
     *
     * @return the value of dream_ORDER.SKILL_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Long getSkillId() {
        return skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.SKILL_ID
     *
     * @param skillId the value for dream_ORDER.SKILL_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setSkillId(Long skillId) {
        this.skillId = skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.SKILL_NAME
     *
     * @return the value of dream_ORDER.SKILL_NAME
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getSkillName() {
        return skillName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.SKILL_NAME
     *
     * @param skillName the value for dream_ORDER.SKILL_NAME
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setSkillName(String skillName) {
        this.skillName = skillName == null ? null : skillName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.SELLER_ID
     *
     * @return the value of dream_ORDER.SELLER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.SELLER_ID
     *
     * @param sellerId the value for dream_ORDER.SELLER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.SELLER_NICK
     *
     * @return the value of dream_ORDER.SELLER_NICK
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getSellerNick() {
        return sellerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.SELLER_NICK
     *
     * @param sellerNick the value for dream_ORDER.SELLER_NICK
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setSellerNick(String sellerNick) {
        this.sellerNick = sellerNick == null ? null : sellerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.BUYER_ID
     *
     * @return the value of dream_ORDER.BUYER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Long getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.BUYER_ID
     *
     * @param buyerId the value for dream_ORDER.BUYER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setBuyerId(Long buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.BUYER_NICK
     *
     * @return the value of dream_ORDER.BUYER_NICK
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.BUYER_NICK
     *
     * @param buyerNick the value for dream_ORDER.BUYER_NICK
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick == null ? null : buyerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.RATE_ID
     *
     * @return the value of dream_ORDER.RATE_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Long getRateId() {
        return rateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.RATE_ID
     *
     * @param rateId the value for dream_ORDER.RATE_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setRateId(Long rateId) {
        this.rateId = rateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.MEETING_TYPE
     *
     * @return the value of dream_ORDER.MEETING_TYPE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Integer getMeetingType() {
        return meetingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.MEETING_TYPE
     *
     * @param meetingType the value for dream_ORDER.MEETING_TYPE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setMeetingType(Integer meetingType) {
        this.meetingType = meetingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.AMOUNT
     *
     * @return the value of dream_ORDER.AMOUNT
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.AMOUNT
     *
     * @param amount the value for dream_ORDER.AMOUNT
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.ORDER_STATUS
     *
     * @return the value of dream_ORDER.ORDER_STATUS
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.ORDER_STATUS
     *
     * @param orderStatus the value for dream_ORDER.ORDER_STATUS
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.VISIBLE_STATUS
     *
     * @return the value of dream_ORDER.VISIBLE_STATUS
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Integer getVisibleStatus() {
        return visibleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.VISIBLE_STATUS
     *
     * @param visibleStatus the value for dream_ORDER.VISIBLE_STATUS
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setVisibleStatus(Integer visibleStatus) {
        this.visibleStatus = visibleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.PAY_STATUS
     *
     * @return the value of dream_ORDER.PAY_STATUS
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.PAY_STATUS
     *
     * @param payStatus the value for dream_ORDER.PAY_STATUS
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.BIZ_TYPE
     *
     * @return the value of dream_ORDER.BIZ_TYPE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.BIZ_TYPE
     *
     * @param bizType the value for dream_ORDER.BIZ_TYPE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setBizType(String bizType) {
        this.bizType = bizType == null ? null : bizType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.PAY_TIME
     *
     * @return the value of dream_ORDER.PAY_TIME
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.PAY_TIME
     *
     * @param payTime the value for dream_ORDER.PAY_TIME
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_ORDER.ATTRIBUTES
     *
     * @return the value of dream_ORDER.ATTRIBUTES
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getAttributes() {
        return attributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_ORDER.ATTRIBUTES
     *
     * @param attributes the value for dream_ORDER.ATTRIBUTES
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setAttributes(String attributes) {
        this.attributes = attributes == null ? null : attributes.trim();
    }
}