package com.sven.dream.dal.trade;

import java.util.Date;

public class DreamSkillDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.GMT_CREATE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.CREATOR
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.GMT_MODIFIED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.MODIFIER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.IS_DELETED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.NAME
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.PIC_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.SELLER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.INTRODUCE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.DOWN_BOUND_PRICE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Long downBoundPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.UP_BOUND_PRICE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Long upBoundPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.NORMAL_PRICE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Long normalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.CATEGORY
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.PER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String per;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.MEETING_TYPE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Integer meetingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_SKILL.RATE_COUNT
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Integer rateCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.ID
     *
     * @return the value of dream_SKILL.ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.ID
     *
     * @param id the value for dream_SKILL.ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.GMT_CREATE
     *
     * @return the value of dream_SKILL.GMT_CREATE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.GMT_CREATE
     *
     * @param gmtCreate the value for dream_SKILL.GMT_CREATE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.CREATOR
     *
     * @return the value of dream_SKILL.CREATOR
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.CREATOR
     *
     * @param creator the value for dream_SKILL.CREATOR
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.GMT_MODIFIED
     *
     * @return the value of dream_SKILL.GMT_MODIFIED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.GMT_MODIFIED
     *
     * @param gmtModified the value for dream_SKILL.GMT_MODIFIED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.MODIFIER
     *
     * @return the value of dream_SKILL.MODIFIER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.MODIFIER
     *
     * @param modifier the value for dream_SKILL.MODIFIER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.IS_DELETED
     *
     * @return the value of dream_SKILL.IS_DELETED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.IS_DELETED
     *
     * @param isDeleted the value for dream_SKILL.IS_DELETED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.NAME
     *
     * @return the value of dream_SKILL.NAME
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.NAME
     *
     * @param name the value for dream_SKILL.NAME
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.PIC_ID
     *
     * @return the value of dream_SKILL.PIC_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.PIC_ID
     *
     * @param picId the value for dream_SKILL.PIC_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setPicId(String picId) {
        this.picId = picId == null ? null : picId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.SELLER_ID
     *
     * @return the value of dream_SKILL.SELLER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.SELLER_ID
     *
     * @param sellerId the value for dream_SKILL.SELLER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.INTRODUCE
     *
     * @return the value of dream_SKILL.INTRODUCE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.INTRODUCE
     *
     * @param introduce the value for dream_SKILL.INTRODUCE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.DOWN_BOUND_PRICE
     *
     * @return the value of dream_SKILL.DOWN_BOUND_PRICE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Long getDownBoundPrice() {
        return downBoundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.DOWN_BOUND_PRICE
     *
     * @param downBoundPrice the value for dream_SKILL.DOWN_BOUND_PRICE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setDownBoundPrice(Long downBoundPrice) {
        this.downBoundPrice = downBoundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.UP_BOUND_PRICE
     *
     * @return the value of dream_SKILL.UP_BOUND_PRICE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Long getUpBoundPrice() {
        return upBoundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.UP_BOUND_PRICE
     *
     * @param upBoundPrice the value for dream_SKILL.UP_BOUND_PRICE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setUpBoundPrice(Long upBoundPrice) {
        this.upBoundPrice = upBoundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.NORMAL_PRICE
     *
     * @return the value of dream_SKILL.NORMAL_PRICE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Long getNormalPrice() {
        return normalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.NORMAL_PRICE
     *
     * @param normalPrice the value for dream_SKILL.NORMAL_PRICE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setNormalPrice(Long normalPrice) {
        this.normalPrice = normalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.CATEGORY
     *
     * @return the value of dream_SKILL.CATEGORY
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.CATEGORY
     *
     * @param category the value for dream_SKILL.CATEGORY
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.PER
     *
     * @return the value of dream_SKILL.PER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getPer() {
        return per;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.PER
     *
     * @param per the value for dream_SKILL.PER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setPer(String per) {
        this.per = per == null ? null : per.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.MEETING_TYPE
     *
     * @return the value of dream_SKILL.MEETING_TYPE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Integer getMeetingType() {
        return meetingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.MEETING_TYPE
     *
     * @param meetingType the value for dream_SKILL.MEETING_TYPE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setMeetingType(Integer meetingType) {
        this.meetingType = meetingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_SKILL.RATE_COUNT
     *
     * @return the value of dream_SKILL.RATE_COUNT
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Integer getRateCount() {
        return rateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_SKILL.RATE_COUNT
     *
     * @param rateCount the value for dream_SKILL.RATE_COUNT
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setRateCount(Integer rateCount) {
        this.rateCount = rateCount;
    }
}