package com.sven.dream.dal.trade;

import java.util.Date;

import com.sven.dream.base.entity.DreamDo;

public class DreamRateDo extends DreamDo{
     
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.RATE_TEXT
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String rateText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.RATE_TIME
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Date rateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.USER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Long userId;
 
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.RATE_TEXT
     *
     * @return the value of dream_RATE.RATE_TEXT
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getRateText() {
        return rateText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.RATE_TEXT
     *
     * @param rateText the value for dream_RATE.RATE_TEXT
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setRateText(String rateText) {
        this.rateText = rateText == null ? null : rateText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.RATE_TIME
     *
     * @return the value of dream_RATE.RATE_TIME
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Date getRateTime() {
        return rateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.RATE_TIME
     *
     * @param rateTime the value for dream_RATE.RATE_TIME
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setRateTime(Date rateTime) {
        this.rateTime = rateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.USER_ID
     *
     * @return the value of dream_RATE.USER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.USER_ID
     *
     * @param userId the value for dream_RATE.USER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}