package com.sven.dream.dal.trade;

import java.util.Date;

public class DreamRateDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.GMT_CREATE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.CREATOR
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.GMT_MODIFIED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.MODIFIER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.IS_DELETED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.RATE_TEXT
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private String rateText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.RATE_TIME
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Date rateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.USER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.ID
     *
     * @return the value of dream_RATE.ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.ID
     *
     * @param id the value for dream_RATE.ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.GMT_CREATE
     *
     * @return the value of dream_RATE.GMT_CREATE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.GMT_CREATE
     *
     * @param gmtCreate the value for dream_RATE.GMT_CREATE
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.CREATOR
     *
     * @return the value of dream_RATE.CREATOR
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.CREATOR
     *
     * @param creator the value for dream_RATE.CREATOR
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.GMT_MODIFIED
     *
     * @return the value of dream_RATE.GMT_MODIFIED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.GMT_MODIFIED
     *
     * @param gmtModified the value for dream_RATE.GMT_MODIFIED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.MODIFIER
     *
     * @return the value of dream_RATE.MODIFIER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.MODIFIER
     *
     * @param modifier the value for dream_RATE.MODIFIER
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.IS_DELETED
     *
     * @return the value of dream_RATE.IS_DELETED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.IS_DELETED
     *
     * @param isDeleted the value for dream_RATE.IS_DELETED
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.RATE_TEXT
     *
     * @return the value of dream_RATE.RATE_TEXT
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public String getRateText() {
        return rateText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.RATE_TEXT
     *
     * @param rateText the value for dream_RATE.RATE_TEXT
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setRateText(String rateText) {
        this.rateText = rateText == null ? null : rateText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.RATE_TIME
     *
     * @return the value of dream_RATE.RATE_TIME
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Date getRateTime() {
        return rateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.RATE_TIME
     *
     * @param rateTime the value for dream_RATE.RATE_TIME
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setRateTime(Date rateTime) {
        this.rateTime = rateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.USER_ID
     *
     * @return the value of dream_RATE.USER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.USER_ID
     *
     * @param userId the value for dream_RATE.USER_ID
     *
     * @mbggenerated Tue Aug 04 17:09:50 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}