package com.sven.dream.dal.order;
 
import com.sven.dream.base.entity.DreamDo;

public class DreamSkillSkuDo extends DreamDo{
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_skill_sku.SELLER_ID
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_skill_sku.SKILL_ID
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    private Long skillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_skill_sku.SKU_CODE
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    private String skuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_skill_sku.TITLE
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_skill_sku.STATUS
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_skill_sku.PRICE
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_skill_sku.PROPERTIES
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    private String properties;
 
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_skill_sku.SELLER_ID
     *
     * @return the value of dream_skill_sku.SELLER_ID
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_skill_sku.SELLER_ID
     *
     * @param sellerId the value for dream_skill_sku.SELLER_ID
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_skill_sku.SKILL_ID
     *
     * @return the value of dream_skill_sku.SKILL_ID
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    public Long getSkillId() {
        return skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_skill_sku.SKILL_ID
     *
     * @param skillId the value for dream_skill_sku.SKILL_ID
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    public void setSkillId(Long skillId) {
        this.skillId = skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_skill_sku.SKU_CODE
     *
     * @return the value of dream_skill_sku.SKU_CODE
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    public String getSkuCode() {
        return skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_skill_sku.SKU_CODE
     *
     * @param skuCode the value for dream_skill_sku.SKU_CODE
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    public void setSkuCode(String skuCode) {
        this.skuCode = skuCode == null ? null : skuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_skill_sku.TITLE
     *
     * @return the value of dream_skill_sku.TITLE
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_skill_sku.TITLE
     *
     * @param title the value for dream_skill_sku.TITLE
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_skill_sku.STATUS
     *
     * @return the value of dream_skill_sku.STATUS
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_skill_sku.STATUS
     *
     * @param status the value for dream_skill_sku.STATUS
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_skill_sku.PRICE
     *
     * @return the value of dream_skill_sku.PRICE
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_skill_sku.PRICE
     *
     * @param price the value for dream_skill_sku.PRICE
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_skill_sku.PROPERTIES
     *
     * @return the value of dream_skill_sku.PROPERTIES
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    public String getProperties() {
        return properties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_skill_sku.PROPERTIES
     *
     * @param properties the value for dream_skill_sku.PROPERTIES
     *
     * @mbggenerated Wed Aug 19 17:05:25 CST 2015
     */
    public void setProperties(String properties) {
        this.properties = properties == null ? null : properties.trim();
    }
}