package com.sven.dream.dal.order;

import java.util.Date;

import com.sven.dream.base.entity.DreamDo;

public class DreamRateDo extends DreamDo{
     
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.SKILL_ID
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    private Long skillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.SKILL_SKU
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    private String skillSku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.USER_ID
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.DISPLAY_USER_NICK
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    private String displayUserNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.RATE_TEXT
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    private String rateText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.RATE_TIME
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    private Date rateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.RATE_LEVEL
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    private Integer rateLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.USEFUL_COUNT
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    private Integer usefulCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dream_RATE.UNUSEFUL_COUNT
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    private Integer unusefulCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.SKILL_ID
     *
     * @return the value of dream_RATE.SKILL_ID
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public Long getSkillId() {
        return skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.SKILL_ID
     *
     * @param skillId the value for dream_RATE.SKILL_ID
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public void setSkillId(Long skillId) {
        this.skillId = skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.SKILL_SKU
     *
     * @return the value of dream_RATE.SKILL_SKU
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public String getSkillSku() {
        return skillSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.SKILL_SKU
     *
     * @param skillSku the value for dream_RATE.SKILL_SKU
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public void setSkillSku(String skillSku) {
        this.skillSku = skillSku == null ? null : skillSku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.USER_ID
     *
     * @return the value of dream_RATE.USER_ID
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.USER_ID
     *
     * @param userId the value for dream_RATE.USER_ID
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.DISPLAY_USER_NICK
     *
     * @return the value of dream_RATE.DISPLAY_USER_NICK
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public String getDisplayUserNick() {
        return displayUserNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.DISPLAY_USER_NICK
     *
     * @param displayUserNick the value for dream_RATE.DISPLAY_USER_NICK
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public void setDisplayUserNick(String displayUserNick) {
        this.displayUserNick = displayUserNick == null ? null : displayUserNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.RATE_TEXT
     *
     * @return the value of dream_RATE.RATE_TEXT
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public String getRateText() {
        return rateText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.RATE_TEXT
     *
     * @param rateText the value for dream_RATE.RATE_TEXT
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public void setRateText(String rateText) {
        this.rateText = rateText == null ? null : rateText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.RATE_TIME
     *
     * @return the value of dream_RATE.RATE_TIME
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public Date getRateTime() {
        return rateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.RATE_TIME
     *
     * @param rateTime the value for dream_RATE.RATE_TIME
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public void setRateTime(Date rateTime) {
        this.rateTime = rateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.RATE_LEVEL
     *
     * @return the value of dream_RATE.RATE_LEVEL
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public Integer getRateLevel() {
        return rateLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.RATE_LEVEL
     *
     * @param rateLevel the value for dream_RATE.RATE_LEVEL
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public void setRateLevel(Integer rateLevel) {
        this.rateLevel = rateLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.USEFUL_COUNT
     *
     * @return the value of dream_RATE.USEFUL_COUNT
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public Integer getUsefulCount() {
        return usefulCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.USEFUL_COUNT
     *
     * @param usefulCount the value for dream_RATE.USEFUL_COUNT
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public void setUsefulCount(Integer usefulCount) {
        this.usefulCount = usefulCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dream_RATE.UNUSEFUL_COUNT
     *
     * @return the value of dream_RATE.UNUSEFUL_COUNT
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public Integer getUnusefulCount() {
        return unusefulCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dream_RATE.UNUSEFUL_COUNT
     *
     * @param unusefulCount the value for dream_RATE.UNUSEFUL_COUNT
     *
     * @mbggenerated Fri Aug 07 10:27:17 CST 2015
     */
    public void setUnusefulCount(Integer unusefulCount) {
        this.unusefulCount = unusefulCount;
    }
}